name: Atualizar Cartola

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Conferir arquivos
        run: |
          pwd
          ls -la
          echo "Arquivos encontrados:"
          find . -maxdepth 4 -type f

      - name: Executar atualização
        run: |
          ARQUIVO=$(find . -name "atualizar_cartola.py" | head -n 1)
          echo "Arquivo encontrado: $ARQUIVO"
          python "$ARQUIVO"

      - name: Salvar histórico
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add historico_cartola.json histórico_cartola.json || true

          git commit -m "Atualiza histórico Cartola" || echo "Nada para atualizar"

          git push
